package:
    name: ecorelevesensor
    version: "0.0.1"
source:
    git_url: https://github.com/NaturalSolutions/ecoReleve-Sensor.git
    git_tag: v0.0.1
# patches:
# List any patch files here
# - fix.patch
# build:
#preserve_egg_dir: True
#entry_points:
# Put any entry points (scripts to be generated automatically) here. The
# syntax is module:function. For example
#
# - bottle = bottle:main
#
# Would create an entry point called bottle that calls bottle.main()
# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
# number: 1

requirements:
    build:
        - pandas
        - python
        - pyodbc
        - pyramid
        - pyramid_tm
        - numpy
        - reportlab
        - setuptools
        - scikit-learn
        - waitress
        - zope.sqlalchemy
    run:
        - python
        - numpy
        - pandas
        - pyodbc
        - pyramid_tm
        - reporlab
        - sqlalchemy
        - scikit-learn
        - waitress
        - zope.sqlalchemy
test:
    # Python imports
    imports:
        - ecorelevesensor
#commands:
# You can put test commands to be run here. Use this to test that the
# entry points work.
# You can also put a file called run_test.py in the recipe that will be run
# at test time.
# requires:
# Put any additional test requirements here. For example
# - nose
about:
    home: http://natural-solutions.eu/
    license: MIT License
# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml